

-- COUNT THE NUMBER OF ACTIONS FOUND
GET_ACTION_COUNT
{
	SELECT COUNT(*) FROM ACTIONS
	WHERE ACTION = '[ACTION]'
}

-- INSERT ROW INTO ACTIONS
INSERT_ACTION
{
	INSERT INTO ACTIONS (DOCUMENTID, ACTION, NAME) 
	VALUES (?, ?, ?)
}

-- IS DOCUMENTID FOR ACTION
IS_DOCUMENT_ACTION
{
	SELECT DOCUMENTID FROM ACTIONS
	WHERE DOCUMENTID = '[DOCUMENTID]'
	AND ACTION = '[ACTION]'
}

-- DELETE A DOCUMENT ACTION
DELETE_ACTION
{
	DELETE FROM ACTIONS
	WHERE DOCUMENTID = ?
	AND ACTION = ?
}

-- GET ALL ACTION DOCUMENTS
GET_ALL_ACTIONS
{
	SELECT DOCUMENTID FROM ACTIONS
	WHERE ACTION = '[ACTION]'
}
