
-- SELECT INCOMING PACKAGE ID BASED ON PACKAGE NAME
GET_INCOMING_PACKAGE_ID_NAME
{
	SELECT ID FROM INCOMING_PACKAGE WHERE NAME = '[NAME]'
}

-- DELETE INCOMING_PACKAGE BY SPECIFIED ID
DELETE_INCOMING_PACKAGE
{
	DELETE FROM INCOMING_PACKAGE WHERE ID = ?
}

-- INSERT ROW INTO INCOMING_PACKAGE
INSERT_INCOMING_PACKAGE
{
	INSERT INTO INCOMING_PACKAGE (ID, NAME, REVISION, STATUSAUTOMATION, ERROR) 
	VALUES (?, ?, ?, ?, ?)
}

-- SELECT CURRENT REVISION BASED ON PACKAGE ID
GET_CURRENT_REVISION
{
	SELECT REVISION FROM INCOMING_PACKAGE WHERE ID = '[PACKAGEID]'
}
