
-- SELECT CUSTOMER ID BASED ON CUSTOMER NUMBER
GET_CUSTOMER_ID
{
	SELECT ID FROM CUSTOMER WHERE CUSTOMERID = '[CUSTOMER_ID]'
}

-- DELETE CUSTOMER BY SPECIFIED ID
DELETE_CUSTOMER
{
	DELETE FROM CUSTOMER WHERE ID = ?
}

-- INSERT ROW INTO CUSTOMER
INSERT_CUSTOMER
{
	INSERT INTO CUSTOMER (ID, NAME, CUSTOMERID, CITY, STATE, COLOR1, COLOR2, COLOR3, MASCOT) 
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
}

