
-- Count rows in the DESIGN table
DESIGN_COUNT
{
	select count(*) 
	from design
}

-- INSERT ROW INTO DESIGN_KEYWORD
INSERT_DESIGN_KEYWORD
{
	INSERT INTO DESIGN_KEYWORD (DESIGN, KEYWORD, SEQUENCE) 
	VALUES (?, ?, ?)
}

-- SELECT KEYWORD ID BASED ON KEYWORD
GET_KEYWORD_ID
{
	SELECT ID FROM KEYWORD WHERE KEYWORD = '[KEYWORD]'
}

-- INSERT ROW INTO KEYWORD
INSERT_KEYWORD
{
	INSERT INTO KEYWORD (ID, KEYWORD) 
	VALUES (?, ?)
}

-- DELETE FROM DESIGN_KEYWORD TABLE FOR SPECIFIED DESIGN
DELETE_DESIGN_KEYWORDS
{
	DELETE FROM DESIGN_KEYWORD WHERE DESIGN = ?
}

-- SELECT DESIGN ID BASED ON DESIGN NAME
GET_DESIGN_ID
{
	SELECT ID FROM DESIGN WHERE NAME = '[NAME]'
}

-- DELETE DESIGN BY SPECIFIED ID
DELETE_DESIGN
{
	DELETE FROM DESIGN WHERE ID = ?
}

-- INSERT ROW INTO DESIGN
INSERT_DESIGN
{
	INSERT INTO DESIGN (ID, NAME) 
	VALUES (?, ?)
}
