-- Statements related to getting image paths in support of the ImageServlet

-- FOR PARTS, GET THE FOLDER PATH
GET_PART_FOLDER_PATH
{
	SELECT B.FOLDER_PATH FROM PACKAGE A
	INNER JOIN ASSET B ON B.PACKAGEID = A.ID
	WHERE PARTID = [PARTID]
	AND ([IMAGECOLOR] = 1 OR ISBESTAVAILABLE = 1)
}

-- FOR CUSTOMERS, GET THE FOLDER PATH
GET_CUSTOMER_FOLDER_PATH
{
	SELECT A.BUSINESS_DEFAULT_USE, B.FOLDER_PATH FROM CUSTOMER_PACKAGE A
	INNER JOIN ASSET B ON B.PACKAGEID = A.PACKAGEID
	WHERE A.CUSTOMERID = [CUSTOMERID]
	AND B.ISBESTAVAILABLE = 1
}
