
-- SELECT PACKAGE ID BASED ON PACKAGE IDENTIFIER
GET_PACKAGE_ID_IDENTIFIER
{
	SELECT ID FROM PACKAGE WHERE IDENTIFIER = '[IDENTIFIER]'
}

-- SELECT PACKAGE ID BASED ON PACKAGE NAME
GET_PACKAGE_ID_NAME
{
	SELECT ID FROM PACKAGE WHERE NAME = '[NAME]'
}

-- DELETE PACKAGE BY SPECIFIED ID
DELETE_PACKAGE
{
	DELETE FROM PACKAGE WHERE ID = ?
}

