
-- SELECT PACKAGE ID BASED ON PACKAGE IDENTIFIER
GET_PACKAGE_ID_IDENTIFIER
{
	SELECT ID FROM PACKAGE WHERE IDENTIFIER = '[IDENTIFIER]'
}

-- SELECT PACKAGE ID BASED ON PACKAGE NAME
GET_PACKAGE_ID_NAME
{
	SELECT ID FROM PACKAGE WHERE NAME = '[NAME]'
}

-- DELETE PACKAGE BY SPECIFIED ID
DELETE_PACKAGE
{
	DELETE FROM PACKAGE WHERE ID = ?
}

-- INSERT ROW INTO PACKAGE
INSERT_PACKAGE
{
	INSERT INTO PACKAGE (ID, NAME, IDENTIFIER, PARTID, FIRSTCUSTOMERID, BRAND_ASSET_TYPE, BASE_COLOR_TONES, ENHANCEMENT_COLOR, COLOR1, COLOR2, COLOR3, COLOR4, COLOR5, COLOR6, COLOR7, COLOR8, COLOR9, COLOR10, BASE_COLOR, COLOR_SCHEME) 
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
}

-- GET PACKAGE BY ID
GET_PACKAGE
{
	SELECT ID, NAME, IDENTIFIER, PARTID, FIRSTCUSTOMERID, BRAND_ASSET_TYPE, BASE_COLOR_TONES, ENHANCEMENT_COLOR, COLOR1, COLOR2, COLOR3, COLOR4, COLOR5, COLOR6, COLOR7, COLOR8, COLOR9, COLOR10, BASE_COLOR, COLOR_SCHEME
	FROM PACKAGE WHERE ID = ?
}

-- DELETE FROM ASSET TABLE FOR SPECIFIED PACKAGEID
DELETE_ASSET_FOR_PACKAGE
{
	DELETE FROM ASSET WHERE PACKAGEID = ?
}

-- INSERT ROW INTO ASSET
INSERT_ASSET_FOR_PACKAGE
{
	INSERT INTO ASSET (PACKAGEID, NAME, FOLDER_PATH, ISBLACK, ISGOLD, ISSILVER, ISBESTAVAILABLE) 
	VALUES (?, ?, ?, ?, ?, ?, ?)
}

-- GET ASSETS FOR A PACKAGE
GET_ASSETS_FOR_PACKAGE
{
	SELECT PACKAGEID, NAME, FOLDER_PATH, ISBLACK, ISGOLD, ISSILVER, ISBESTAVAILABLE
	FROM ASSET
	WHERE PACKAGEID = ?
}

-- DELETE THE SPECIFIED CUSTOMER PACKAGE PROVIDED WITH A CUSTOMER ID AND A PACKAGE ID
DELETE_CUSTOMER_PACKAGE
{
	DELETE FROM CUSTOMER_PACKAGE WHERE PACKAGEID = ? AND CUSTOMERID = ?
}

-- INSERT ROW INTO CUSTOMER_PACKAGE
INSERT_CUSTOMER_PACKAGE
{
	INSERT INTO CUSTOMER_PACKAGE (ID, PACKAGEID, CUSTOMERID, AFFILIATION_BY_USE, HISTORIC_USE_COLOR, HISTORIC_USE_DESIGN, STATUS_LIFE_CYCLE, STATUS_CATALOGING, STATUS_AUTOMATION, STATUS_AVAILABILITY, BUSINESS_DEFAULT_USE) 
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
}

-- SELECT PACKAGE ID FOR ALL PACKAGES
GET_ALL_PACKAGEIDS
{
	SELECT ID FROM PACKAGE
}

-- SELECT CUSTOMER_PACKAGE ID BASED ON PACKAGEID AND CUSTOMERID
GET_CUSTOMER_PACKAGE_ID
{
	SELECT ID FROM CUSTOMER_PACKAGE WHERE PACKAGEID = '[PACKAGEID]' AND CUSTOMERID = '[CUSTOMERID]'
}

-- GET customer PACKAGE BY ID
GET_CUSTOMER_PACKAGE
{
	SELECT ID, PACKAGEID, CUSTOMERID, AFFILIATION_BY_USE, HISTORIC_USE_COLOR, HISTORIC_USE_DESIGN, STATUS_LIFE_CYCLE, STATUS_CATALOGING, STATUS_AUTOMATION, STATUS_AVAILABILITY, BUSINESS_DEFAULT_USE
	FROM CUSTOMER_PACKAGE WHERE ID = ?
}
