
-- SELECT PACKAGE ID BASED ON PACKAGE IDENTIFIER
GET_PACKAGE_ID_IDENTIFIER
{
	SELECT ID FROM PACKAGE WHERE IDENTIFIER = '[IDENTIFIER]'
}

-- SELECT PACKAGE ID BASED ON PACKAGE NAME
GET_PACKAGE_ID_NAME
{
	SELECT ID FROM PACKAGE WHERE NAME = '[NAME]'
}

-- DELETE PACKAGE BY SPECIFIED ID
DELETE_PACKAGE
{
	DELETE FROM PACKAGE WHERE ID = ?
}

-- INSERT ROW INTO PACKAGE
INSERT_PACKAGE
{
	INSERT INTO PACKAGE (ID, NAME, IDENTIFIER, PARTID, FIRSTCUSTOMERID, BRAND_ASSET_TYPE, BASE_COLOR_TONES, ENHANCEMENT_COLOR, COLOR1, COLOR2, COLOR3, COLOR4, COLOR5, COLOR6, COLOR7, COLOR8, COLOR9, COLOR10, BASE_COLOR, COLOR_SCHEME) 
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
}
