
-- INSERT ROW INTO PART
INSERT_PART
{
	INSERT INTO PART (ID, NAME, DESIGNID_STRING, JOSTENSID_STRING, PARTID, PARTID_DERIVATIVE, PART_VALIDATION, DESIGNID) 
	VALUES (?, ?, ?, ?, ?, ?, ?, ?)
}

-- GET PART BY ID
GET_DESIGN
{
	SELECT ID, NAME, AFFILITION_BY_DEPICTION, DESIGNID, JOSTENSID, BRAND_ASSET_TYPE, CREATIVE_INTENT_DESIGN, DISPLAYED_INITIALS, DISPLAYED_NAME, DISPLAYED_MASCOT, DISPLAYED_MOTTO, DISPLAYED_INSCRIPTION, DISPLAYED_YEAR_DATE, EXTEND_OF_USABILITY, FUNCTIONAL_INTENT, MAIN_SUBJECT, MULTIPLE_MAIN_SUBJECT, PORTION_MAIN_SUBJECT, VIEW_MAIN_SUBJECT
	FROM DESIGN WHERE ID = ?
}

-- SELECT PART ID BASED ON PART NAME
GET_PART_ID
{
	SELECT ID FROM PART WHERE NAME = '[NAME]'
}

-- DELETE PART BY SPECIFIED ID
DELETE_PART
{
	DELETE FROM PART WHERE ID = ?
}

