
-- Statements related to the search functionality

-- TAKE THE START OF A PACKAGE NAME (PART) AND FIND ALL CUSTOMER NUMBERS USING THAT PART
GET_CUSTOMER_FROM_PART
{
	SELECT C.CUSTOMERID FROM PACKAGE A
	INNER JOIN CUSTOMER_PACKAGE B ON B.PACKAGEID = A.ID
	INNER JOIN CUSTOMER C ON C.ID = B.CUSTOMERID
	WHERE A.NAME LIKE '[PART_NAME]%'
}

