--
-- CREATE ALL JEMM2 DATABASE OBJECTS
--
-- THIS IS JUST A QUICK POST TO SHARE THESE 2 LITTLE SHORTCUTS TO CONVERT TEXT FROM LOWER CASE TO UPPERCASE AND VICEVERSA IN ECLIPSE.
-- LOWER CASE: CTRL+SHIFT+Y (CMD+SHIFT+Y ON MAC OS X)
-- UPPER CASE: CTRL+SHIFT+X (CMD+SHIFT+X ON MAC OS X)



--
-- DESIGN
-- 		THIS TABLE IS AN ASSET DESIGN, THE LOWEST LEVEL OBJECT
--
DROP TABLE DESIGN;
CREATE TABLE DESIGN 
(
	ID NUMBER NOT NULL ENABLE,
	NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
	AFFILITION_BY_DEPICTION VARCHAR2(100 BYTE),
	DESIGNID VARCHAR2(100 BYTE),
	JOSTENSID VARCHAR2(100 BYTE),
	BRAND_ASSET_TYPE VARCHAR2(100 BYTE),
	CREATIVE_INTENT_DESIGN VARCHAR2(100 BYTE),
	DISPLAYED_INITIALS VARCHAR2(100 BYTE),
	DISPLAYED_NAME VARCHAR2(100 BYTE),
	DISPLAYED_MASCOT VARCHAR2(100 BYTE),
	DISPLAYED_MOTTO VARCHAR2(300 BYTE),
	DISPLAYED_INSCRIPTION VARCHAR2(200 BYTE),
	DISPLAYED_YEAR_DATE VARCHAR2(100 BYTE),
	EXTEND_OF_USABILITY VARCHAR2(100 BYTE),
	FUNCTIONAL_INTENT VARCHAR2(100 BYTE),
	MAIN_SUBJECT VARCHAR2(100 BYTE),
	MULTIPLE_MAIN_SUBJECT VARCHAR2(100 BYTE),
	PORTION_MAIN_SUBJECT VARCHAR2(100 BYTE),
	VIEW_MAIN_SUBJECT VARCHAR2(100 BYTE),
	
	CONSTRAINT "DESIGN_PK" PRIMARY KEY ("ID")
);

--
-- KEYWORD
-- 		THIS TABLE IS A KEYWORD
--
DROP TABLE KEYWORD;
CREATE TABLE KEYWORD 
(
	ID NUMBER NOT NULL ENABLE,
	KEYWORD VARCHAR2(50 BYTE) NOT NULL ENABLE,
	
	CONSTRAINT "KEYWORD_PK" PRIMARY KEY ("ID")
);

--
-- DESIGN_KEYWORD
-- 		THIS TABLE RELATES DESIGNS TO KEYWORDS
--
DROP TABLE DESIGN_KEYWORD;
CREATE TABLE DESIGN_KEYWORD 
(
	DESIGN NUMBER NOT NULL ENABLE,
	KEYWORD_ID NUMBER NOT NULL ENABLE,
	SEQUENCE NUMBER,
	
	CONSTRAINT "UNIQUE_1" UNIQUE ("DESIGN", "KEYWORD_ID")
);

------------------------------------ SEQUENCES

-- SEQUENCE FOR ID COLUMN OF DESIGN TABLE
DROP SEQUENCE DESIGN_SEQUENCE;
CREATE SEQUENCE DESIGN_SEQUENCE 
START WITH 1 
INCREMENT BY 1 
NOCACHE
NOMAXVALUE;

-- SEQUENCE FOR ID COLUMN OF KEYWORD TABLE
DROP SEQUENCE KEYWORD_SEQUENCE;
CREATE SEQUENCE KEYWORD_SEQUENCE 
START WITH 1 
INCREMENT BY 1 
NOCACHE
NOMAXVALUE;
