--
-- CREATE ALL JEMM2 DATABASE OBJECTS
--
-- THIS IS JUST A QUICK POST TO SHARE THESE 2 LITTLE SHORTCUTS TO CONVERT TEXT FROM LOWER CASE TO UPPERCASE AND VICEVERSA IN ECLIPSE.
-- LOWER CASE: CTRL+SHIFT+Y (CMD+SHIFT+Y ON MAC OS X)
-- UPPER CASE: CTRL+SHIFT+X (CMD+SHIFT+X ON MAC OS X)



--
-- DESIGN
-- 		THIS TABLE IS AN ASSET DESIGN, THE LOWEST LEVEL OBJECT
--
DROP TABLE DESIGN;
CREATE TABLE DESIGN 
(
	ID NUMBER NOT NULL ENABLE,
	NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
	
	CONSTRAINT "DESIGN_PK" PRIMARY KEY ("ID")
);

--
-- KEYWORD
-- 		THIS TABLE IS A KEYWORD
--
DROP TABLE KEYWORD;
CREATE TABLE KEYWORD 
(
	ID NUMBER NOT NULL ENABLE,
	KEYWORD VARCHAR2(50 BYTE) NOT NULL ENABLE,
	
	CONSTRAINT "KEYWORD_PK" PRIMARY KEY ("ID")
);

--
-- DESIGN_KEYWORD
-- 		THIS TABLE RELATES DESIGNS TO KEYWORDS
--
DROP TABLE DESIGN_KEYWORD;
CREATE TABLE DESIGN_KEYWORD 
(
	DESIGN NUMBER NOT NULL ENABLE,
	KEYWORD NUMBER NOT NULL ENABLE,
	SEQUENCE NUMBER,
	
	CONSTRAINT "UNIQUE_1" UNIQUE ("DESIGN", "KEYWORD")
);

------------------------------------ SEQUENCES

-- SEQUENCE FOR ID COLUMN OF DESIGN TABLE
DROP SEQUENCE DESIGN_SEQUENCE;
CREATE SEQUENCE DESIGN_SEQUENCE 
START WITH 1 
INCREMENT BY 1 
NOCACHE
NOMAXVALUE;

-- SEQUENCE FOR ID COLUMN OF KEYWORD TABLE
DROP SEQUENCE KEYWORD_SEQUENCE;
CREATE SEQUENCE KEYWORD_SEQUENCE 
START WITH 1 
INCREMENT BY 1 
NOCACHE
NOMAXVALUE;
