--
-- CREATE ALL JEMM2 AUTOMATION DATABASE OBJECTS
--
-- THIS IS JUST A QUICK POST TO SHARE THESE 2 LITTLE SHORTCUTS TO CONVERT TEXT FROM LOWER CASE TO UPPERCASE AND VICEVERSA IN ECLIPSE.
-- LOWER CASE: CTRL+SHIFT+Y (CMD+SHIFT+Y ON MAC OS X)
-- UPPER CASE: CTRL+SHIFT+X (CMD+SHIFT+X ON MAC OS X)

--
-- INCOMINGPACKAGE
-- 		THIS TABLE HOLDS INFORMATION ABOUT ASSET PACKAGES BEING PROCESSED BY AUTOMATIONS
--
DROP TABLE INCOMINGPACKAGE;
CREATE TABLE INCOMINGPACKAGE 
(
	ID NUMBER NOT NULL ENABLE,
	NAME VARCHAR2(250 BYTE) NOT NULL ENABLE,
	STATUSAUTOMATION VARCHAR2(300 BYTE),
	
	CONSTRAINT "INCOMINGPACKAGE_PK" PRIMARY KEY ("ID")
);

------------------------------------ SEQUENCES

-- SEQUENCE FOR ID COLUMN OF INCOMINGPACKAGE TABLE
DROP SEQUENCE INCOMINGPACKAGE_SEQUENCE;
CREATE SEQUENCE INCOMINGPACKAGE_SEQUENCE 
START WITH 1 
INCREMENT BY 1 
NOCACHE
NOMAXVALUE;
