--
-- CREATE ALL JEMM2 ACTION DATABASE OBJECTS
--
-- THIS IS JUST A QUICK POST TO SHARE THESE 2 LITTLE SHORTCUTS TO CONVERT TEXT FROM LOWER CASE TO UPPERCASE AND VICEVERSA IN ECLIPSE.
-- LOWER CASE: CTRL+SHIFT+Y (CMD+SHIFT+Y ON MAC OS X)
-- UPPER CASE: CTRL+SHIFT+X (CMD+SHIFT+X ON MAC OS X)

--
-- BOOKMARK
-- 		THIS TABLE HOLDS REFERENCE TO OBJECTS WHICH HAVE BEEN BOOKMARKED
--
DROP TABLE BOOKMARK;
CREATE TABLE BOOKMARK 
(
	DOCUMENTID VARCHAR2(250 BYTE) NOT NULL ENABLE
);
