--
-- CREATE ALL JEMM2 ACTION DATABASE OBJECTS
--
-- THIS IS JUST A QUICK POST TO SHARE THESE 2 LITTLE SHORTCUTS TO CONVERT TEXT FROM LOWER CASE TO UPPERCASE AND VICEVERSA IN ECLIPSE.
-- LOWER CASE: CTRL+SHIFT+Y (CMD+SHIFT+Y ON MAC OS X)
-- UPPER CASE: CTRL+SHIFT+X (CMD+SHIFT+X ON MAC OS X)

--
-- ACTIONS
-- 		THIS TABLE HOLDS REFERENCE TO OBJECTS WHICH HAVE HAD AN ACTION ON THEM SUCH AS BOOKMARK, DOWNLOAD, QUARANTINE, ETC... 
--
DROP TABLE ACTIONS;
CREATE TABLE ACTIONS 
(
	DOCUMENTID VARCHAR2(20 BYTE) NOT NULL ENABLE,
	ACTION VARCHAR2(20 BYTE) NOT NULL ENABLE,
	NAME VARCHAR2(250 BYTE)

);
