--
-- CREATE ALL JEMM2 PART DATABASE OBJECTS
--
-- THIS IS JUST A QUICK POST TO SHARE THESE 2 LITTLE SHORTCUTS TO CONVERT TEXT FROM LOWER CASE TO UPPERCASE AND VICEVERSA IN ECLIPSE.
-- LOWER CASE: CTRL+SHIFT+Y (CMD+SHIFT+Y ON MAC OS X)
-- UPPER CASE: CTRL+SHIFT+X (CMD+SHIFT+X ON MAC OS X)



--
-- PART
-- 		THIS TABLE IS A PART WHICH USES AN ASSET DESIGN, 
--
DROP TABLE PART;
CREATE TABLE PART 
(
	ID NUMBER NOT NULL ENABLE,
	NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
	DESIGNID_STRING VARCHAR2(100 BYTE),
	JOSTENSID_STRING VARCHAR2(100 BYTE),
	PARTID VARCHAR2(100 BYTE),
	PARTID_DERIVATIVE VARCHAR2(100 BYTE),
	PART_VALIDATION VARCHAR2(100 BYTE),
	DESIGNID NUMBER,
	
	CONSTRAINT "PART_PK" PRIMARY KEY ("ID")
);

------------------------------------ SEQUENCES

-- SEQUENCE FOR ID COLUMN OF part TABLE
DROP SEQUENCE PART_SEQUENCE;
CREATE SEQUENCE PART_SEQUENCE 
START WITH 1 
INCREMENT BY 1 
NOCACHE
NOMAXVALUE;
